name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable

    - name: Set binary filename (Windows)
      if: matrix.os == 'windows-latest'
      run: echo "binary_name=mineshare.exe" >> $GITHUB_ENV
      shell: pwsh

    - name: Set binary filename (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: echo "binary_name=mineshare" >> $GITHUB_ENV
      shell: bash

    - name: Build release
      run: cargo build --release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-binary
        path: target/release/${{env.binary_name}}

