name: Main

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            ext: ""
            os: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            ext: ""
            os: ubuntu-latest

          - target: x86_64-apple-darwin
            ext: ""
            os: macos-latest
          - target: aarch64-apple-darwin
            ext: ""
            os: macos-latest

          - target: x86_64-pc-windows-msvc
            ext: ".exe"
            os: windows-latest
          - target: aarch64-pc-windows-msvc
            ext: ".exe"
            os: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install MUSL tools if needed
        if: contains(matrix.target, 'musl')
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools gcc-aarch64-linux-gnu
          export RUSTFLAGS="-C target-feature=+crt-static"
          export AWS_LC_SYS_C_STD=11 

      - name: Build
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Package
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/mineshare${{ matrix.ext }} dist/mineshare-${{ matrix.target }}${{ matrix.ext }}
          cp target/${{ matrix.target }}/release/mineshare_server${{ matrix.ext }} dist/mineshare_server-${{ matrix.target }}${{ matrix.ext }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: |
            dist/mineshare-${{ matrix.target }}${{ matrix.ext }}
            dist/mineshare_server-${{ matrix.target }}${{ matrix.ext }}

      - name: Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/mineshare-${{ matrix.target }}${{ matrix.ext }}
            dist/mineshare_server-${{ matrix.target }}${{ matrix.ext }}
